### Itero API
POST http://localhost:8080/api/itero/login
Content-Type: application/json

###
GET http://localhost:8080/api/itero/status

###
GET http://localhost:8080/api/itero/commandes

###
POST http://localhost:8080/api/itero/logout
Content-Type: application/json




### ThreeShape API
POST http://localhost:8080/api/threeshape/login
Content-Type: application/json

###
GET http://localhost:8080/api/threeshape/status

###
POST http://localhost:8080/api/threeshape/logout

###
GET http://localhost:8080/api/threeshape/commandes




### Dexis IsConnect API
POST http://localhost:8080/api/dexis-isconnect/login
Content-Type: application/json
###
GET http://localhost:8080/api/dexis-isconnect/status
###
POST http://localhost:8080/api/dexis-isconnect/logout
Content-Type: application/json
###
GET http://localhost:8080/api/dexis-isconnect/commandes



### MeditLink API
POST http://localhost:8080/api/meditlink/login
Content-Type: application/json

###
GET http://localhost:8080/api/meditlink/status

###
GET http://localhost:8080/api/meditlink/commandes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjc0NTEyOCwiZXhwIjoxNzUyODMxNTI4fQ.Kx2KfJiLnNsy0UfD-soI2zKvkdaiBlNRDCu9VsYNZtQ


###
POST http://localhost:8080/api/meditlink/logout
Content-Type: application/json


### Commandes API
GET http://localhost:8080/api/commandes

### Création de compte
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Jean",
  "lastName": "Dupont",
  "email": "jean.dupont@exemple.com",
  "password": "Password123!",
  "phone": "+33612345678",
  "country": "FR",
  "companyType": "dentiste",
  "newsletter": true
}

### connexion
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "jean.dupont@exemple.com",
  "password": "Password123!"
}

### Utilisateur connecté

GET http://localhost:8080/api/auth/user/jean.dupont@exemple.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg



### Création d'une plateforme (authentification requise)
POST http://localhost:8080/api/platforms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

{
  "name": "Itero",
  "email": "3shape@test.com",
  "password": "iteroPass123",
  "userId": 1
}

### Récupérer toutes les plateformes d'un utilisateur
GET http://localhost:8080/api/platforms/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

### Mettre à jour une plateforme
PUT http://localhost:8080/api/platforms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

{
  "name": "Itero Pro",
  "email": "itero.pro@test.com",
  "password": "newPassword123",
  "userId": 1
}

### Supprimer une plateforme
DELETE http://localhost:8080/api/platforms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

