### Itero API
POST http://localhost:8080/api/itero/login
Content-Type: application/json

###
GET http://localhost:8080/api/itero/status

###
GET http://localhost:8080/api/itero/commandes
###
POST http://localhost:8080/api/itero/logout
Content-Type: application/json




### ThreeShape API
POST http://localhost:8080/api/threeshape/login
Content-Type: application/json

###
GET http://localhost:8080/api/threeshape/status

###
POST http://localhost:8080/api/threeshape/logout

###
GET http://localhost:8080/api/threeshape/commandes




### Dexis IsConnect API
POST http://localhost:8080/api/dexis-isconnect/login
Content-Type: application/json
###
GET http://localhost:8080/api/dexis-isconnect/status
###
POST http://localhost:8080/api/dexis-isconnect/logout
Content-Type: application/json
###
GET http://localhost:8080/api/dexis-isconnect/commandes



### MeditLink API
POST http://localhost:8080/api/meditlink/login
Content-Type: application/json

###
GET http://localhost:8080/api/meditlink/status

###
GET http://localhost:8080/api/meditlink/commandes

###
POST http://localhost:8080/api/meditlink/logout
Content-Type: application/json
