### Itero API
POST http://localhost:8080/api/itero/login
Content-Type: application/json

###
GET http://localhost:8080/api/itero/status

###
GET http://localhost:8080/api/itero/commandes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1MzE4Nzk5NCwiZXhwIjoxNzUzMjc0Mzk0fQ.wOlH-QToU2Rsou-qtHAYgtgkJGjwWjmXXktuyszekRU

###
POST http://localhost:8080/api/itero/logout
Content-Type: application/json




### ThreeShape API
POST http://localhost:8080/api/threeshape/login
Content-Type: application/json

###
GET http://localhost:8080/api/threeshape/status

###
POST http://localhost:8080/api/threeshape/logout

###
GET http://localhost:8080/api/threeshape/commandes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1MzE4OTU3NCwiZXhwIjoxNzUzMjc1OTc0fQ.HsDaMAa0fhSKMWym43nXB5tyYH6tgoCpzOvbBAQB27w




### Dexis IsConnect API
POST http://localhost:8080/api/dexis-isconnect/login
Content-Type: application/json
###
GET http://localhost:8080/api/dexis-isconnect/status
###
POST http://localhost:8080/api/dexis-isconnect/logout
Content-Type: application/json
###
GET http://localhost:8080/api/dexis-isconnect/commandes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1MzE4NTg1MCwiZXhwIjoxNzUzMjcyMjUwfQ.jv_WI3DON2ZQaIL1wqSLIdx6NsWXIhAxhOCmi7I4nhk



### MeditLink API
POST http://localhost:8080/api/meditlink/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1MzE3ODA3NSwiZXhwIjoxNzUzMjY0NDc1fQ.X4cuVv5BHhxENWzx-x_4pEdU89TuDlUpx3GO19JLwFE

###
GET http://localhost:8080/api/meditlink/status

###
GET http://localhost:8080/api/meditlink/commandes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1MzI2MDIwOCwiZXhwIjoxNzUzMzQ2NjA4fQ.224msMx89i8Cdp33gux14NF5ReudPAY4QcV5Qb_OiIM
###
POST http://localhost:8080/api/meditlink/logout
Content-Type: application/json


### Commandes API
GET http://localhost:8080/api/commandes

### Création de compte
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstName": "Jean",
  "lastName": "Dupont",
  "email": "jean.dupont@exemple.com",
  "password": "Password123!",
  "phone": "+33612345678",
  "country": "FR",
  "companyType": "dentiste",
  "newsletter": true
}

### connexion
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "jean.dupont@exemple.com",
  "password": "Password123!"
}

### Utilisateur connecté

GET http://localhost:8080/api/auth/user/jean.dupont@exemple.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg



### Création d'une plateforme (authentification requise)
POST http://localhost:8080/api/platforms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

{
  "name": "Itero",
  "email": "3shape@test.com",
  "password": "iteroPass123",
  "userId": 1
}

### Récupérer toutes les plateformes d'un utilisateur
GET http://localhost:8080/api/platforms/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

### Mettre à jour une plateforme
PUT http://localhost:8080/api/platforms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

{
  "name": "Itero Pro",
  "email": "itero.pro@test.com",
  "password": "newPassword123",
  "userId": 1
}

### Supprimer une plateforme
DELETE http://localhost:8080/api/platforms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1Mjg0NTEyNywiZXhwIjoxNzUyOTMxNTI3fQ.e1dBuvgczuId3YCz7z9nSfzQ2ogEt7WrHOoq0i2LuTg

### Commentaire d'une commande spécifique
GET http://localhost:8080/api/meditlink/commentaire/20156204
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1MzE3MTEwMiwiZXhwIjoxNzUzMjU3NTAyfQ.D80Q5dhKkCtGjWUx4d2L98hDZrDl-6HIph9cOQqzVyY

### Tous les commentaires
GET http://localhost:8080/api/meditlink/commentaires
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWFuLmR1cG9udEBleGVtcGxlLmNvbSIsImlhdCI6MTc1MzE3NDQxMCwiZXhwIjoxNzUzMjYwODEwfQ.muLIYQbX-ijHKKdSSXN3C1T7vWM4YbF5rL2E909-Hng

